### ISSUE TITLE
Ignoring windows run from application shortcut

### ISSUE THREAD

**Issue by orschiro** [sindresorhus/merge-windows#1]
Hi @sindresorhus,

Thank you very much for your simple yet effective extension!

I have one question:

Would it be possible to add an option that ignores all windows that were launched from `Tools -> Create Application shortcut`?

Thankfully,

Robert

**Comment by sindresorhus** [comment]
Why? And is there any way to detect such windows?

**Comment by orschiro** [comment]
@sindresorhus 

> Why?

The tool is a great way to create app-like windows that nicely integrate into the system. For instance, I did that with gmail.com and now it provides me with a native-feel email client. Such windows shouldn't be merged since they are not really considered windows containing tabs. 

> And is there any way to detect such windows?

I would have no idea but asked the question on stackoverflow:

http://stackoverflow.com/questions/31122451/is-it-possible-to-detect-chrome-windows-that-were-created-from-application-short

Let's see. Thanks for your quick response!

Robert

**Comment by orschiro** [comment]
Works great. Thank you very much!
