### ISSUE TITLE
Exclude progressive web apps from being merged

### ISSUE THREAD

**Issue by schana** [sindresorhus/merge-windows#8]
Currently, if a PWA is opened, it is merged into the chrome window. It would be desirable if this was not the case, as it ruins the distinct "app" nature of whatever was merged. For example, YouTube Music or Google Chat.

**Comment by sindresorhus** [comment]
What exactly do you mean by PWA? "More Tools => Create Shortcut"? Can you provide an example? Because this extension already just fetches normal windows, so not sure how it would detect a PWA.

**Comment by schana** [comment]
Before the merge, YouTube Music is in its own window as a progressive web app:
<img width="962" alt="before merge" src="https://user-images.githubusercontent.com/9595417/102725811-d8793e80-4319-11eb-96eb-08df2ff44d9b.png">
After merge, it's converted to a tab in the browser:
<img width="962" alt="after merge" src="https://user-images.githubusercontent.com/9595417/102725812-da430200-4319-11eb-83f0-0b8937989c0d.png">

**Comment by sindresorhus** [comment]
I'm happy to accept a pull request to fix this, but it's unclear to me whether this is a bug in Chrome or if not, whether it's even possible to detect this.

**Comment by schana** [comment]
Looks like the root cause is that the PWAs have a windowType of `popup`, and I'm not sure of a good way to detect whether it's an app or a popup with the information the extension api gives.

**Comment by szhu** [comment]
Turns out the code explicitly looks for tabs belonging to PWAs, so this was surprisingly easy to fix.

https://github.com/sindresorhus/merge-windows/pull/10

**Comment by schana** [comment]
This is no longer an issue. For YouTube Music at least, the tab now has a windowType of `app`, so the code works as-is.
